.TH "airspyhf_info" 1 "2020.08.10" AIRSPYHF "User Commands"
.SH NAME
airspyhf_info \- probe device and show configuration
.SH DESCRIPTION
The AirspyHF is a tiny and efficient software defined radio receiver.
.LP
This application lets the user probe the device and show configuration.
.SH SYNOPSIS
.B  airspyhf_info
.SH OPTIONS
.SS "Usage:"
.HP
\fB\-s\fR serial number: open receiver with specified 64 bits serial number.
.SH SEE ALSO
AirspyHF web page:
.B https://airspy.com/airspy-hf-plus
.LP
Other airspyhf programs:
.sp
airspyhf_rx(1), airspyhf_gpio(1), airspyhf_lib_version(1), airspyhf_rx(1)
.SH AUTHOR
This manual page was written by Maitland Bottoms
for the Debian project (but may be used by others).
.SH COPYRIGHT
Copyright (c) 2020 A. Maitland Bottoms <bottoms@debian.org>
.LP
This program is free software: you can redistribute it and/or modify
it under the terms of the GNU General Public License as published by
the Free Software Foundation, either version 2 of the License, or
(at your option) any later version.
.LP
This program is distributed in the hope that it will be useful,
but WITHOUT ANY WARRANTY; without even the implied warranty of
MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.  See the
GNU General Public License for more details.
